version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql-data:/var/lib/mysql  # Mount the SQL file to initialize the database
    networks:
      - lms_network  # Attach the MySQL service to the lms_network

  flaskapp:
    image: flaskapp:v1
    build: .
    container_name: flaskapp
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - lms_network  # Attach the Flask app service to the lms_network

networks:
  lms_network:  # Define a custom network named lms_network
